apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.serviceName }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.postgres.dbName }}
  DB_USER: {{ .Values.postgres.dbUser }}
  DB_PASSWORD: {{ .Values.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
    .Values.dockerhub.username
    .Values.dockerhub.password
    (printf "%s:%s" .Values.dockerhub.username .Values.dockerhub.password | b64enc)
    | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
type: Opaque
stringData:
  secret-key: {{ .Values.django.secretKey }}
  database-url: {{ printf "postgresql://%s:%s@postgres:5432/%s" 
    .Values.postgres.dbUser
    .Values.postgres.dbPassword
    .Values.postgres.dbName }}