services:
  user-service:
    # image:
    #   tag: "a1b2c3f"     # ← CI writes this
    replicas: 1
  order-service:
    # image:
    #   tag: "a1b2c3f"
    replicas: 1
  payment-service:
    # image:
    #   tag: "a1b2c3f"
    replicas: 1

postgres:
  storageSize: 2Gi