# Generated by Django 4.2.9 on 2026-03-17 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_booking_updates', models.BooleanField(default=True)),
                ('email_trip_updates', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_reviews', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_booking_updates', models.BooleanField(default=True)),
                ('sms_trip_updates', models.BooleanField(default=True)),
                ('sms_payment_updates', models.BooleanField(default=False)),
                ('push_booking_updates', models.BooleanField(default=True)),
                ('push_trip_updates', models.BooleanField(default=True)),
                ('push_payment_updates', models.BooleanField(default=True)),
                ('push_reviews', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('payment_received', 'Payment Received'), ('payout_processed', 'Payout Processed'), ('review_received', 'Review Received'), ('driver_verified', 'Driver Verified'), ('driver_rejected', 'Driver Rejected'), ('no_show_penalty', 'No Show Penalty'), ('cancellation_warning', 'Cancellation Warning'), ('account_suspended', 'Account Suspended'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_trip_id', models.IntegerField(blank=True, null=True)),
                ('related_booking_id', models.IntegerField(blank=True, null=True)),
                ('related_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_sent_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
