accountsService:
  replicas: 1

driversService:
  replicas: 1

notificationsService:
  replicas: 1

paymentsService:
  replicas: 1

reviewsService:
  replicas: 1

tripsService:
  replicas: 1

postgres:
  storageSize: 2Gi
  dbName: rideshare_db
  dbUser: samandar
  dbPassword: Samandar0405@

django:
  secretKey: "django-insecure-dev-key-change-in-production"

dockerHub:
  username: "18c336445927"
  password: ""

imagePullSecrets:
  - name: dockerhub-secret